name: Download Artifact

on:
  push:
    branches:
    - 'main'

jobs:
  Download_artifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: my-artifact
    
    - name: Display structure of downloaded files
      run: ls -R
